---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.7.0
git:
  submodules: false
before_install:
  - gem install bundler -v 2.1.2
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
