#define PLUS                             1
#define MINUS                            2
#define DIVIDE                           3
#define TIMES                            4
#define AMPER                            5
#define COMMA                            6
#define INTEGER                          7
#define IDENTIFIER                       8
#define CONSTANT                         9
#define FID                             10
#define NL                              11
#define SEMICOLON                       12
